"""Aggregate analytics helpers so downstream consumers can import from `quantalytics.analytics`."""

from .metrics import calmar, gain_to_pain_ratio, kurtosis, omega, sharpe, skew, sortino
from .stats import (
    avg_loss,
    avg_return,
    avg_win,
    best,
    cagr,
    comp,
    compsum,
    consecutive_losses,
    consecutive_wins,
    distribution,
    expected_return,
    exposure,
    geometric_mean,
    ghpr,
    max_drawdown,
    outliers,
    remove_outliers,
    rolling_volatility,
    volatility,
    win_rate,
    worst,
)

__all__: list[str] = [
    "sharpe",
    "sortino",
    "compsum",
    "comp",
    "distribution",
    "expected_return",
    "geometric_mean",
    "ghpr",
    "outliers",
    "remove_outliers",
    "best",
    "worst",
    "consecutive_wins",
    "consecutive_losses",
    "exposure",
    "win_rate",
    "avg_return",
    "avg_win",
    "avg_loss",
    "volatility",
    "rolling_volatility",
    "max_drawdown",
    "calmar",
    "omega_ratio",
    "gain_to_pain_ratio",
    "skew",
    "kurtosis",
    "annualized_return",
    "annualized_volatility",
    "cagr",
    "omega",
    "gain_to_pain_ratio",
    "skew",
    "kurtosis",
]
